'use strict';

const ORDER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  PACKED: 'PACKED',
  DISPATCHED: 'DISPATCHED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED',
  REFUNDED: 'REFUNDED',
});

// Allowed forward transitions for the order status machine.
const ORDER_STATUS_TRANSITIONS = Object.freeze({
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.PACKED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PACKED]: [ORDER_STATUS.DISPATCHED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.DISPATCHED]: [ORDER_STATUS.OUT_FOR_DELIVERY, ORDER_STATUS.RETURNED],
  [ORDER_STATUS.OUT_FOR_DELIVERY]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.RETURNED],
  [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.RETURNED],
  [ORDER_STATUS.RETURNED]: [ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.CANCELLED]: [],
  [ORDER_STATUS.REFUNDED]: [],
});

const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  CANCELLED: 'CANCELLED',
});

const PRESCRIPTION_STATUS = Object.freeze({
  UPLOADED: 'UPLOADED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  VERIFIED: 'VERIFIED',
  NEEDS_CLARIFICATION: 'NEEDS_CLARIFICATION',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  FULFILLED: 'FULFILLED',
});

const PRESCRIPTION_STATUS_TRANSITIONS = Object.freeze({
  [PRESCRIPTION_STATUS.UPLOADED]: [PRESCRIPTION_STATUS.UNDER_REVIEW],
  [PRESCRIPTION_STATUS.UNDER_REVIEW]: [
    PRESCRIPTION_STATUS.VERIFIED,
    PRESCRIPTION_STATUS.NEEDS_CLARIFICATION,
    PRESCRIPTION_STATUS.REJECTED,
  ],
  [PRESCRIPTION_STATUS.NEEDS_CLARIFICATION]: [
    PRESCRIPTION_STATUS.UNDER_REVIEW,
    PRESCRIPTION_STATUS.REJECTED,
  ],
  [PRESCRIPTION_STATUS.VERIFIED]: [PRESCRIPTION_STATUS.ACCEPTED, PRESCRIPTION_STATUS.REJECTED],
  [PRESCRIPTION_STATUS.ACCEPTED]: [PRESCRIPTION_STATUS.FULFILLED],
  [PRESCRIPTION_STATUS.REJECTED]: [],
  [PRESCRIPTION_STATUS.FULFILLED]: [],
});

module.exports = {
  ORDER_STATUS,
  ORDER_STATUS_TRANSITIONS,
  PAYMENT_STATUS,
  PRESCRIPTION_STATUS,
  PRESCRIPTION_STATUS_TRANSITIONS,
};
