'use strict';

const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  ORDER_MANAGER: 'ORDER_MANAGER',
  PHARMACY_MANAGER: 'PHARMACY_MANAGER',
  DOCTOR: 'DOCTOR',
  CUSTOMER_SUPPORT: 'CUSTOMER_SUPPORT',
  DELIVERY_MANAGER: 'DELIVERY_MANAGER',
  REPORT_MANAGER: 'REPORT_MANAGER',
  CUSTOMER: 'CUSTOMER',
});

const STAFF_ROLES = Object.freeze(
  Object.values(ROLES).filter((r) => r !== ROLES.CUSTOMER && r !== ROLES.DOCTOR)
);

const ADMIN_ROLES = Object.freeze([ROLES.SUPER_ADMIN, ROLES.ADMIN]);

module.exports = { ROLES, STAFF_ROLES, ADMIN_ROLES };
